# Generated by Django 4.1.3 on 2023-01-04 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_files', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('number_of_categories', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='Allowed size is 24.0 MBs', upload_to='PN_files/%Y/%m/%d/', verbose_name='Files')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.modeltrainingparams'),
        ),
    ]
