# Generated by Django 4.1.3 on 2023-01-09 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='PN_files/%Y/%m/%d/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Files'),
        ),
    ]
