# Generated by Django 4.1.3 on 2022-12-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_trainingmodel_modeltrainingparams_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltrainingparams',
            old_name='num_categories',
            new_name='number_of_categories',
        ),
    ]
