# Generated by Django 4.1.3 on 2022-12-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_remove_category_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, help_text='Allowed size is 24.0 MBs', upload_to='PN_files/%Y/%m/%d/', verbose_name='Files'),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
