# Generated by Django 4.1.3 on 2022-12-27 22:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_category_file_delete_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Allowed size is 24.0 MBs', storage=django.core.files.storage.FileSystemStorage(location='/media/imgs'), upload_to='', verbose_name='Files')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.category')),
            ],
        ),
    ]
